splash = false

wallpaper {
  monitor = LVDS-1
  path = ~/pictures/backgrounds/nord_rider.png
  fit_mode = cover
}

wallpaper {
  monitor = VGA-1
  path = ~/pictures/backgrounds/nord_rider.png
  fit_mode = cover
}
